import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import MainHeader from "@/components/main-header/main-header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MainHeader />
        {children}
      </body>
    </html>
  );
}
